<?php echo $this->doctype(); ?>

<html lang="en_US">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Tamkang Univercity '. $this->translate('Information Management Department'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    </head>
    <body class="font">
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner navbar-inverse main-nav">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="main-brand brand" href="<?php echo $this->url("en_US/default"); ?>"></a>
                    <div class="nav-collapse collapse navigation">
                        <?php echo $this->navigation('navigation/en_us')->menu()->setPartial($partial = array('template/navigation', 'default')) ?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div>
            <?php echo $this->content; ?>
            <hr>
        </div>
        <div class="container">
            <footer class="row">
                <div class="span3">
                    Phone: 26215656-2645 or 2648<br/>
                    Tex: （02）26209737<br/>
                    E-Mail：tlmx@oa.tku.edu.tw
                </div>
                <div class="span9 content">
                    <a href="<?php echo $this->url("zh_TW/default"); ?>">中文版</a> &middot; 
                    <a href="#">About us</a> &middot; 
                    <a href="http://www.tku.edu.tw/">TKU</a> &middot;
                    <a href="http://www.tku.edu.tw/pdp.asp">Personal Data Policy</a> &middot;
                    <a href="http://www.tku.edu.tw/notify.asp">Notify</a> &middot;
                    <a href="http://www.tku.edu.tw/privacy.asp">Privacy</a> &middot;
                    <a href="<?php echo $this->url("admin"); ?>">Admin System</a>
                    <br/>
                    &copy; 2013 Tamkang IM, <a href="http://calvinpeak.net">Calvin</a> &amp; <a href="http://qugoid.tumblr.com/">Sam</a>.
                </div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->appendFile($this->basePath() . '/js/affix.js'); ?>
        <script>
            $('.carousel').carousel();
        </script>
    </body>
</html>
