<div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                分類項目
            </a>
        </div>
        <div class="col-sm-3 col-xs-6 sidebar-offcanvas">
            <form class="input-group search-form" method="get" action="<?php echo $this->url("zh_TW/default", array("controller" => "news")); ?>">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </span>
                <?php if (isset($this->typeId)) : ?>
                    <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                <?php endif; ?>
                <input class="form-control search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="輸入關鍵字查詢消息" />
            </form>
            <ul class="nav nav-list bs-docs-sidenav">
                <li><a href="<?php echo $this->url("zh_TW/default", array("controller" => "news")); ?>"><i class="icon-chevron-right"></i>全部</a></li>
                <?php foreach ($this->articleTypes as $i => $articleType) : ?>
                    <li class="<?php echo ($this->typeId == $articleType["id"]) ? "active" : "" ?>">
                        <a href="<?php echo $this->url("zh_TW/default", array("controller" => "news")) . "?type=" . $articleType["id"]; ?>">
                            <i class="fa fa-chevron-right pull-right"></i>
                            <?php echo $articleType["type_name"]; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header">
                <?php echo $this->title; ?>
                <small class="pull-right text-muted">
                    <i class="fa fa-clock-o"></i>
                    <?php echo $this->time; ?>
                </small>
            </h4>
            <?php echo $this->content; ?>
            <hr>
            <?php if (count($this->images) > 0) : ?>
                <div class="attach-title">
                    <i class="fa fa-file-image-o"></i>&nbsp;文章附圖
                    <a class="btn btn-default btn-small pull-right" id="stretch-all">展開所有圖片</a>
                </div>
                <div>
                    <?php foreach ($this->images as $i => $image) : ?>
                        <a data-src="<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $image["image_name"]; ?>" class="attach attach-image">
                            <label>
                                <i class="fa fa-resize"></i>&nbsp;
                                點擊展開圖片
                            </label>
                        </a>
                    <?php endforeach; ?>
                </div>
                <hr>
            <?php endif; ?>
            <?php if (count($this->downloads) > 0) : ?>
                <div class="attach-title">
                    <i class="fa fa-file"></i>&nbsp;文章附檔
                    <a class="btn btn-default btn-small pull-right disabled" href="#<?php // echo $this->url("application/default", array("controller" => "file", "action" => "package")) . "?article_id" . $this->articleId; ?>">下載所有檔案</a>
                </div>
                <div>
                    <?php foreach ($this->downloads as $i => $download) : ?>
                        <a class="attach attach-download" href="<?php echo $this->url("application/default", array("controller" => "file")) . "?" . $download["file_name"]; ?>">
                            <label>
                                <i class="icon-download-alt"></i>&nbsp;
                                <?php echo $download["download_name"]; ?>
                            </label>
                        </a>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>