<div class="container">
    <div class="row  row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                分類項目
            </a>
        </div>
        <div class="col-sm-3 col-xs-6 sidebar-offcanvas">
            <form class="input-group search-form" method="get" action="<?php echo $this->url("zh_TW/default", array("controller" => "news")); ?>">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </span>
                <?php if (isset($this->typeId)) : ?>
                    <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                <?php endif; ?>
                <input class="form-control search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="輸入關鍵字查詢消息" />
            </form>
            <ul class="nav nav-list bs-docs-sidenav">
                <li><a href="<?php echo $this->url("zh_TW/default", array("controller" => "news")); ?>"><i class="icon-chevron-right"></i>全部</a></li>
                <?php foreach ($this->articleTypes as $i => $articleType) : ?>
                    <li class="<?php echo ($this->typeId == $articleType["id"]) ? "active" : "" ?>">
                        <a href="<?php echo $this->url("zh_TW/default", array("controller" => "news")) . "?type=" . $articleType["id"]; ?>">
                            <i class="fa fa-chevron-right pull-right"></i>
                            <?php echo $articleType["type_name"]; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header articles-header">
                <i class="fa fa-info fa-fw"></i>
                消息列表
                <span class="pull-right btn-group">
                    <a class="btn btn-default active" data-toggle="tooltip" data-placement="top" data-container="body" title="消息列表" href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "index")); ?>"><i class="fa fa-list"></i></a>
                    <a class="btn btn-default" data-toggle="tooltip" data-placement="top" data-container="body" title="文件查找" href="<?php echo $this->url("zh_TW/default", array("controller" => "file", "action" => "search")); ?>"><i class="fa fa-file"></i></a>
                </span>
            </h4>
            <div class="row">
        	    <div class="span12">
        	        <?php foreach ($this->articles as $i => $article) : ?>
                    <div class="col-xs-12">
                        <div class="article <?php echo ($article["top"] == 1)? "top" : "" ?>">
                            <div class="article-body">
                                <a href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>">
                                    <h4>
                                        <?php echo $article["title"]; ?>
                                        <?php if ($article["top"] == 1): ?>
                                            <small class="label label-default">置頂</small>
                                        <?php endif; ?>
                                        <small class="pull-right"><i class="fa fa-clock-o fa-fw"></i><?php echo date("Y /m/d", strtotime($article["time"])); ?></small>
                                    </h4>
                                </a>
                                <p class="text-muted"><?php echo $article["content"]; ?></p>
                            </div>
                            <a class="article-view-btn" href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>">
                                <i class="fa fa-angle-right fa-3x"></i>
                            </a>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
        	</div>
        	<div class="text-center">
                <?php echo $this->paginator; ?>
            </div>
        </div>
    </div>
</div>