<form action="<?php echo $this->url("admin/default", array("controller" => "user", "action" => "edit")) . "?id=" . $this->id; ?>" method="post">
    <table class="table table-hover">
        <tr>
            <td>帳號</td>
            <td><?php echo $this->user["username"]; ?></td>
        </tr>
        <tr>
            <td>使用者姓名</td>
            <td><input id="name" name="name" type="text" value="<?php echo $this->user["name"]; ?>" /></td>
        </tr>
        <tr>
            <td>密碼</td>
            <td><input id="new-password" name="password" type="password" class="ignore" placeholder="請輸入新密碼" /></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td><input id="email" name="email" type="email" value="<?php echo $this->user["email"]; ?>" /></td>
        </tr>
        <tr>
            <td>帳號權限</td>
            <td>
                <select id="role" name="role">
                    <?php foreach ($this->roleList as $key => $value) : ?>
                        <option value="<?php echo $value["id"]; ?>" <?php echo ($this->user["role_id"] == $value["id"]) ? "selected" : ""; ?>><?php echo $value["zh_TW"]; ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
    </table>
    <input id="t" name="t" type="hidden" value="<?php echo $this->token; ?>" />
</form>