<div class="btn-toolbar">
    <a class="btn btn-primary" id="add-user" data-toggle="modal" href="<?php echo $this->url("admin/default", array(
        "controller" => "user",
        "action" => "add",
    )); ?>" data-target="#modal-add">新增使用者</a>
    <form class="input-prepend input-append pull-right">
        <button type="submit" class="btn"><i class="icon-search"></i></button>
        <input class="search" type="text" name="term" placeholder="輸入姓名或帳號查詢用戶" value="<?php echo (isset($this->term)) ? htmlentities($this->term, ENT_QUOTES, "UTF-8") : "";?>" />
        <div class="btn-group">
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url("admin/default", array("controller" => "user")); ?>">查看全部</a></li>
                <?php $roleName = ""; ?>
                <?php foreach ($this->roleList as $key => $value) : ?>
                    <li>
                        <a href="<?php echo $this->url("admin/default", array("controller" => "user")) . "?role=" . $value["id"]; ?>">
                            <?php echo $value["zh_TW"]; ?>
                        </a>
                        <?php ($this->role == $value["id"]) ? $roleName = $value["zh_TW"] : ""; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                <?php echo (isset($this->role) && $this->role != "") ? $roleName : "限定等級"; ?>
                <span class="caret"></span>
            </button>
        </div>
    </form>
</div>
<table class="table table-striped">
    <tr>
        <th style="width:15%">帳號</th>
        <th style="width:15%">姓名</th>
        <th>信箱</th>
        <th style="width:15%;">等級</th>
        <th style="width:20%;"></th>
    </tr>
    <?php foreach ($this->userList as $key => $value) : ?>
    <tr>
        <td><?php echo $value["username"]; ?></td>
        <td><?php echo $value["name"]; ?></td>
        <td><?php echo $value["email"]; ?></td>
        <td><?php echo $value["zh_TW"]; ?></td>
        <td>
            <a class="btn" href="<?php echo $this->url("admin/default", array(
                    "controller" => "user",
                    "action" => "edit",
                )) . "?id=" . $value["id"]; ?>"
                data-toggle="modal"
                data-target="#modal-edit"
            >修改</a>
            
            <a class="btn btn-danger" href="<?php echo $this->url("admin/default", array(
                    "controller" => "user",
                    "action" => "delete",
                )) . "?id=" . $value["id"]; ?>"
                data-toggle="modal"
                data-target="#modal-delete"
            >刪除</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<div class="pagination pagination-small pagination-centered"><?php echo $this->paginator; ?></div>