<form class="form-horizontal" method="post" action="<?php echo $this->url("admin/default", array("controller" => "article", "action" => "articletype")); ?>">
    <div class="btn-toolbar">
        <button type="submit" class="btn btn-danger">儲存文章類別</button>
        <a class="btn" href="<?php echo $this->url("admin/default", array("controller" => "article", "action" => "index")); ?>">取消</a>
    </div>
    <?php if ($this->saveSuccess) :?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <i class="icon-ok"></i>&nbsp;儲存成功
    </div>
    <?php endif; ?>
    <?php foreach ($this->articletypeList as $key => $value) : ?>
    <div class="control-group">
        <button type="button" class="close pull-left" data-dismiss="alert">&times;</button>
        <label class="control-label" for="data-index-<?php echo $key + 1; ?>">種類<?php echo $key + 1; ?></label>
        <div class="controls controls-row">
            <input type="text" class="field span3" id="data-index-<?php echo $key + 1; ?>" name="type[]" value="<?php echo $value["type_name"]; ?>" />
            <select class="span2" name="language[]">
                <?php foreach ($this->languageList as $i => $language) : ?>
                    <option value="<?php echo $language["id"]; ?>"<?php echo ($language["id"] == $value["language_id"]) ? " selected" : ""; ?>><?php echo $language["language"]; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php endforeach; ?>
    <div class="control-group">
        <label class="control-label">種類</label>
        <div class="controls controls-row">
            <input type="text" class="field span3" id="data-index-<?php echo count($this->articletypeList) + 1; ?>" name="type[]" value="" />
            <select class="span2" name="language[]">
                <?php foreach ($this->languageList as $i => $language) : ?>
                    <option value="<?php echo $language["id"]; ?>"><?php echo $language["language"]; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</form>