<div class="btn-toolbar">
    <a class="btn btn-primary" id="add-article" data-toggle="modal" href="<?php echo $this->url("admin/default", array(
        "controller" => "article",
        "action" => "add",
    )); ?>" data-target="#modal-add">新增文章</a>
    <form class="input-prepend input-append pull-right">
        <button type="submit" class="btn"><i class="icon-search"></i></button>
        <input class="search" type="text" name="term" placeholder="輸入標題或內容查詢文章" value="<?php echo (isset($this->term)) ? htmlentities($this->term, ENT_QUOTES, "UTF-8") : "";?>" />
        <div class="btn-group">
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url("admin/default", array("controller" => "article")); ?>">查看全部</a></li>
                <li><a href="<?php echo $this->url("admin/default", array("controller" => "article")). "?visible=1"; ?>">顯示</a></li>
                <li><a href="<?php echo $this->url("admin/default", array("controller" => "article")). "?visible=0"; ?>">不顯示</a></li>
            </ul>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                <?php echo (isset($this->visible) && $this->visible != "") ? (($this->visible == 1) ? "顯示" : "不顯示") : "限定狀態"; ?>
                <span class="caret"></span>
            </button>
        </div>
    </form>
</div>
<table class="table table-striped">
    <tr>
        <th style="width:25%;">標題</th>
        <th>內容</th>
        <th style="width:5%;">狀態</th>
        <th style="width:10%;">類別</th>
        <th style="width:10%;">建立時間</th>
        <th style="width:15%;"></th>
    </tr>
    <?php foreach ($this->articleList as $key => $value) : ?>
    <tr>
        <td><?php echo $value["title"]; ?></td>
        <td><?php echo $value["content"]; ?></td>
        <td><?php echo ($value["visible"] == 1) ? ($value["top"] == 1)? "<span class=\"text-error\">置頂</span>" : "顯示" : "不顯示"; ?></td>
        <td><?php echo $value["type_name"]; ?></td>
        <td><?php echo date("Y-m-d", strtotime($value["create_time"])); ?></td>
        <td>
            <a class="btn" href="<?php echo $this->url("admin/default", array(
                    "controller" => "article",
                    "action" => "edit",
                )) . "?id=" . $value["id"]; ?>"
                data-toggle="modal"
                data-target="#modal-edit"
            >修改</a>
            
            <a class="btn btn-danger" href="<?php echo $this->url("admin/default", array(
                    "controller" => "article",
                    "action" => "delete",
                )) . "?id=" . $value["id"]; ?>"
                data-toggle="modal"
                data-target="#modal-delete"
            >刪除</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<div class="pagination pagination-small pagination-centered"><?php echo $this->paginator; ?></div>