<div class="container">
    <div class="row">
        <div class="col-sm-4 col-xs-12">
            <?php if (isset($this->faculty["avatar"]) && $this->faculty["avatar"] != "") : ?>
            <img class="img-responsive profile-img"
                src="<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $this->faculty["avatar"]; ?>">
            <?php else : ?>
                <img class="img-responsive profile-img" src="/images/avatar.jpg">
            <?php endif; ?>
        </div>
        <div class="col-sm-8 col-xs-12">
            <h3>
                <?php echo htmlentities($this->faculty["name"], ENT_QUOTES, "UTF-8"); ?>
                <small class="text-muted"><?php echo htmlentities($this->faculty["title_name"], ENT_QUOTES, "UTF-8"); ?></small>
            </h3>
            <table class="table">
                <?php if (count($this->othertitles) > 0) : ?>
                    <tr>
                        <td>兼任職稱</td>
                        <td>
                            <?php foreach ($this->othertitles as $i => $othertitle) : ?>
                                <p><?php echo htmlentities($othertitle["title_name"], ENT_QUOTES, "UTF-8"); ?></p>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if (isset($this->faculty["teach_class"]) && $this->faculty["teach_class"] != "") : ?>
                    <tr>
                        <td>指導班級</td>
                        <td><?php echo htmlentities($this->faculty["teach_class"], ENT_QUOTES, "UTF-8"); ?></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td>電子信箱</td>
                    <td><?php echo htmlentities($this->faculty["email"], ENT_QUOTES, "UTF-8"); ?></td>
                </tr>
                <?php if (isset($this->faculty["lab_location"]) && $this->faculty["lab_location"] != "") : ?>
                    <tr>
                        <td>研究室位置</td>
                        <td><?php echo htmlentities($this->faculty["lab_location"], ENT_QUOTES, "UTF-8"); ?></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td>研究室網頁</td>
                    <td>
                        <?php if (isset($this->faculty["labsite_url"]) && $this->faculty["labsite_url"] != "") : ?>
                            <a href="<?php echo htmlentities($this->faculty["labsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                <?php echo htmlentities($this->faculty["labsite_text"], ENT_QUOTES, "UTF-8"); ?>
                            </a>
                        <?php else : ?>
                            <a href="#" class="link-disabled">None</a>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td>個人網頁</td>
                    <td>
                        <?php if (isset($this->faculty["personalsite_url"]) && $this->faculty["personalsite_url"] != "") : ?>
                        <a href="<?php echo htmlentities($this->faculty["personalsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                            <?php echo htmlentities($this->faculty["personalsite_text"], ENT_QUOTES, "UTF-8"); ?>
                        </a>
                        <?php else : ?>
                            <a href="#" class="link-disabled">None</a>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <!-- personal information start -->
        <div class="col-sm-4 col-xs-6">
            <h4>
                <i class="fa fa-graduation-cap"></i>
                <?php echo $this->profileTypes[0]["type_name"]; ?>
            </h4>
            <ul class="list-unstyled">
                <?php if (count($this->profiles[$this->profileTypes[0]["id"]]) <= 0) : ?>
                    <li>
                        <h4 class="text-center">
                            <i class="fa fa-exclamation"></i>
                            暫無資料
                        </h4>
                    </li>
                <?php else : ?>
                    <?php foreach ($this->profiles[$this->profileTypes[0]["id"]] as $j => $profile) : ?>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i>
                            <?php echo $profile["profile"]; ?>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
        <div class="col-sm-4 col-xs-6">
            <h4>
                <i class="fa fa-tags"></i>
                <?php echo $this->profileTypes[1]["type_name"]; ?>
            </h4>
            <ul class="list-unstyled">
                <?php if (count($this->profiles[$this->profileTypes[1]["id"]]) <= 0) : ?>
                    <li>
                        <h4 class="text-center">
                            <i class="fa fa-exclamation"></i>
                            暫無資料
                        </h4>
                    </li>
                <?php else : ?>
                    <?php foreach ($this->profiles[$this->profileTypes[1]["id"]] as $j => $profile) : ?>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i>
                            <?php echo $profile["profile"]; ?>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
        <div class="col-sm-4 col-xs-6">
            <h4>
                <i class="fa fa-cog"></i>
                <?php echo $this->profileTypes[2]["type_name"]; ?>
            </h4>
            <ul class="list-unstyled">
                <?php if (count($this->profiles[$this->profileTypes[2]["id"]]) <= 0) : ?>
                    <li>
                        <h4 class="text-center">
                            <i class="fa fa-exclamation"></i>
                            暫無資料
                        </h4>
                    </li>
                <?php else : ?>
                    <?php foreach ($this->profiles[$this->profileTypes[2]["id"]] as $j => $profile) : ?>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i>
                            <?php echo $profile["profile"]; ?>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <div class="row" style="margin-top: 30px;">
        <!-- personal information end -->
        <div class="col-sm-3 col-xs-6 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav margin-top-0">
                <?php foreach($this->bookTypes as $i => $bookType): ?>
                    <li class="<?php echo ($bookType["id"] == $this->typeId) ? "active" : ""; ?>">
                        <a href="<?php echo $this->url("zh_TW/default", array("controller" => "faculty", "action" => "profile")) . "?id=" . $this->id . "&type-id=" . $bookType["id"]; ?>">
                            <i class="icon-chevron-right"></i>
                            <?php echo htmlentities($bookType["type_name"], ENT_QUOTES, "UTF-8"); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col-sm-9 col-xs-12"">
            <table class="table">
                <?php foreach($this->books as $i => $book): ?>
                    <tr>
                        <td>
                            <?php if (isset($book["url"])) : ?>
                                <a target="_blank" href="<?php echo htmlentities($book["url"], ENT_QUOTES, "UTF-8"); ?>">
                                    <?php echo htmlentities($book["title"], ENT_QUOTES, "UTF-8"); ?>
                                </a>
                            <?php else : ?>
                                <?php echo htmlentities($book["title"], ENT_QUOTES, "UTF-8"); ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>