<div class="container">
    <div class="row" style="margin-top: 10px;">
        <div class="row-fluid span12">
            <div class="span4">
                <?php if (isset($this->faculty["avatar"]) && $this->faculty["avatar"] != "") : ?>
                <img class="img-polaroid featurette-image pull-left" style="height:200px;"
                    src="<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $this->faculty["avatar"]; ?>">
                <?php else : ?>
                    <img class="img-polaroid featurette-image pull-left" style="height:200px;" src="" data-src="holder.js/200x200">
                <?php endif; ?>
            </div>
            <div class="span8">
                <h3>
                    <?php echo htmlentities($this->faculty["name"], ENT_QUOTES, "UTF-8"); ?>
                    <span class="muted"><?php echo htmlentities($this->faculty["title_name"], ENT_QUOTES, "UTF-8"); ?></span>
                </h3>
                <table class="table">
                    <tr>
                        <td style="width:45%;">擔任職位</td>
                        <td><?php echo htmlentities($this->faculty["title_name"], ENT_QUOTES, "UTF-8"); ?></td>
                    </tr>
                    <?php if (count($this->othertitles) > 0) : ?>
                        <tr>
                            <td>其他職位</td>
                            <td>
                                <?php foreach ($this->othertitles as $i => $othertitle) : ?>
                                    <p><?php echo htmlentities($othertitle["title_name"], ENT_QUOTES, "UTF-8"); ?></p>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($this->faculty["teach_class"]) && $this->faculty["teach_class"] != "") : ?>
                        <tr>
                            <td>指導班級</td>
                            <td><?php echo htmlentities($this->faculty["teach_class"], ENT_QUOTES, "UTF-8"); ?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td>電子信箱</td>
                        <td><?php echo htmlentities($this->faculty["email"], ENT_QUOTES, "UTF-8"); ?></td>
                    </tr>
                    <?php if (isset($this->faculty["lab_location"]) && $this->faculty["lab_location"] != "") : ?>
                        <tr>
                            <td>研究室位置</td>
                            <td><?php echo htmlentities($this->faculty["lab_location"], ENT_QUOTES, "UTF-8"); ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($this->faculty["labsite_url"]) && $this->faculty["labsite_url"] != "") : ?>
                        <tr>
                            <td>研究室網頁</td>
                            <td>
                                <a href="<?php echo htmlentities($this->faculty["labsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                    <?php echo htmlentities($this->faculty["labsite_text"], ENT_QUOTES, "UTF-8"); ?>
                                </a>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($this->faculty["personalsite_url"]) && $this->faculty["personalsite_url"] != "") : ?>
                        <tr>
                            <td>個人網頁</td>
                            <td>
                                <a href="<?php echo htmlentities($this->faculty["personalsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                    <?php echo htmlentities($this->faculty["personalsite_text"], ENT_QUOTES, "UTF-8"); ?>
                                </a>
                            </td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
        <?php foreach ($this->profileTypes as $i => $profileType) : ?>
            <div class="span<?php echo 12 / count($this->profileTypes); ?>">
                <h4><?php echo $profileType["type_name"]; ?></h4>
                <table class="table table-hover">
                    <?php foreach ($this->profiles[$profileType["id"]] as $j => $profile) : ?>
                    <tr>
                        <td><?php echo $profile["profile"]; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endforeach; ?>
        <div class="page-header span12">
            <h3>教師專書&nbsp;<span class="muted">BOOKS</span></h3>
        </div>
        <?php foreach($this->bookTypeList as $key => $value) : ?>
            <?php if (count($this->bookList[$value["id"]]) > 0) : ?>
                <div class="span12">
                    <h4><?php echo $value["type_name"]; ?></h4>
                    <table class="table table-striped">
                        <?php foreach ($this->bookList[$value["id"]] as $childkey => $childvalue) : ?>
                        <tr>
                            <td><?php echo $childvalue["title"]; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                    <hr>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>