<div class="container">
    <div class="row">
        <div class="span3">
            <div id="nav-side" class="bs-docs-sidenav" style="box-shadow:none;">
                <form class="input-prepend" method="get" action="<?php echo $this->url("application/default", array("controller" => "news")); ?>">
                    <button type="submit" class="btn"><i class="icon-search"></i></button>
                    <input class="search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="輸入關鍵字查詢消息" />
                    <?php if (isset($this->typeId)) : ?>
                        <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                    <?php endif; ?>
                </form>
                <ul class="nav nav-list bs-docs-sidenav">
                    <li><a href="<?php echo $this->url("application/default", array("controller" => "news")); ?>"><i class="icon-chevron-right"></i>全部</a></li>
                    <?php foreach ($this->articleTypes as $i => $articleType) : ?>
                        <li class="<?php echo ($this->typeId == $articleType["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("application/default", array("controller" => "news")) . "?type=" . $articleType["id"]; ?>"><i class="icon-chevron-right"></i><?php echo $articleType["type_name"]; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    
        <div class="content span9">
            <div class="page-header">
                <h3 class="title">
                    消息列表
                    <span class="pull-right btn-group">
                        <a class="btn active" data-toggle="tooltip" data-placement="bottom" data-container="body" title="消息列表"><i class="icon-th-list"></i></a>
                        <a class="btn" data-toggle="tooltip" data-placement="bottom" data-container="body" title="文件查找" href="<?php echo $this->url("application/default", array("controller" => "file", "action" => "search")); ?>"><i class="icon-file"></i></a>
                    </span>
                </h3>
            </div>
            <div class="row-fluid"  style="margin-top: 20px;">
        	    <div class="span12">
        	        <?php foreach ($this->articles as $i => $article) : ?>
        	            <div class="row-fluid">
        	                <div class="featurette span8">
        	                    <hr>
        	                    <h4 class="timestamp">
        	                        <?php echo $article["time"]; ?>
        	                    </h4>
                        		<h2 class="featurette-heading highlight">
                        		    <?php echo strip_tags($article["title"]); ?>
                        		</h2>
                        		<p class="featurette-content highlight">
                        		    <?php echo $article["content"]; ?>
                        		</p>
                                <a href="<?php echo $this->url("application/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>" class="btn">詳細全文</a>
                        	</div>
                        	<div class="span4">
                            	<?php if ($article["title_image"] != "") : ?>
                            	    <div class="article-image-preview" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $article["title_image"]; ?>)">
                            	    </div>
                        	    <?php endif; ?>
                        	</div>
        	            </div>
                	<?php endforeach; ?>
                </div>
        	</div>
        	<div class="pagination pagination-centered">
                <?php echo $this->paginator; ?>
            </div>
        </div>
    </div>
</div>