<div class="container">
    <div class="row">
        <div class="span3">
            <div id="nav-side" class="bs-docs-sidenav" style="box-shadow:none;">
                <form class="input-prepend" method="get" action="<?php echo $this->url("application/default", array("controller" => "file", "action" => "search")); ?>">
                    <button type="submit" class="btn"><i class="icon-search"></i></button>
                    <input class="search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="輸入關鍵字查詢文件" />
                    <?php if (isset($this->typeId)) : ?>
                        <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                    <?php endif; ?>
                </form>
                <ul class="nav nav-list bs-docs-sidenav">
                    <li><a href="<?php echo $this->url("application/default", array("controller" => "file", "action" => "search")); ?>"><i class="icon-chevron-right"></i>全部</a></li>
                    <?php foreach ($this->articleTypes as $i => $articleType) : ?>
                        <li class="<?php echo ($this->typeId == $articleType["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("application/default", array("controller" => "file", "action" => "search")) . "?type=" . $articleType["id"]; ?>"><i class="icon-chevron-right"></i><?php echo $articleType["type_name"]; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        
        <div class="content span9">
            <div class="page-header">
                <h3 class="title">
                    <?php if (isset($this->term) && $this->term != "") : ?>
                        查詢結果
                    <?php else: ?>
                        文件查找
                    <?php endif; ?>
                    <span class="pull-right btn-group">
                        <a class="btn" data-toggle="tooltip" data-placement="bottom" data-container="body" title="消息列表" href="<?php echo $this->url("application/default", array("controller" => "news", "action" => "index")); ?>"><i class="icon-th-list"></i></a>
                        <a class="btn active" data-toggle="tooltip" data-placement="bottom" data-container="body" title="文件查找"><i class="icon-file"></i></a>
                    </span>
                </h3>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th class="span6">文章標題</th>
                        <th class="span6">附屬文件</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->downloads as $i => $download) : ?>
                        <tr>
                            <td><?php echo $download["title"]; ?></td>
                            <td>
                                <a class="attach attach-download" href="<?php echo $this->url("application/default", array("controller" => "file")) . "?" . $download["file_name"]; ?>">
                                    <label class="highlight">
                                        <i class="icon-download-alt"></i>&nbsp;
                                        <?php echo $download["download_name"]; ?>
                                    </label>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="pagination pagination-centered pagination-small">
                <?php echo $this->pagination; ?>
            </div>
            <?php if (count($this->similars) > 0) : ?>
                <hr>
                <h4>以文章標題及內容查詢</h4>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="span6">文章標題</th>
                            <th class="span6">附屬文件</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->similars as $i => $similar) : ?>
                            <tr>
                                <td class="highlight"><?php echo $similar["title"]; ?></td>
                                <td>
                                    <a class="attach attach-download" href="<?php echo $this->url("application/default", array("controller" => "file")) . "?" . $similar["file_name"]; ?>">
                                        <label>
                                            <i class="icon-download-alt"></i>&nbsp;
                                            <?php echo $similar["download_name"]; ?>
                                        </label>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </div>
</div>