<?php echo $this->doctype(); ?>

<html lang="zh_TW">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('淡江大學 '. $this->translate('資訊管理學系'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url("admin/default"); ?>">管理後台</a>
                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation('navigation/admin')->menu()->setPartial($partial = array('template/navigation', 'default')); ?>
                        <ul class="nav pull-right">
                            <li>
                                <div class="thumbnail avatar-small"
                                    <?php if (isset($this->avatar)) : ?> 
                                        style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $this->avatar; ?>)"
                                    <?php else : ?>
                                        style="background-color:#EEEEEE;"
                                    <?php endif; ?>
                                ></div>
                            </li>
                            <li><a href="<?php echo $this->url("admin/default", array("controller" => "auth", "action" => "logout")); ?>">登出</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 Design and Develop by <a href="http://calvinpeak.net">Calvin</a>.</p>
            </footer>
        </div> <!-- /container -->
        
        <!-- Modal -->
        <div id="modal-add" class="modal hide fade" tabindex="-1">
        	<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">×</button>
        		<i class="icon-plus"></i>
        	</div>
        	<div class="modal-body">
        	    <div class="loading"></div>
        	</div>
        	<div class="modal-footer">
        		<button class="btn" data-dismiss="modal">關閉</button>
        		<button class="btn btn-primary" id="action-add">完成</button>
        	</div>
        </div>
        
        <!-- Modal -->
        <div id="modal-delete" class="modal hide fade" tabindex="-1">
        	<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">×</button>
        		<i class="icon-trash"></i>
        	</div>
        	<div class="modal-body">
        	    <div class="loading"></div>
        	</div>
        	<div class="modal-footer">
        		<button class="btn" data-dismiss="modal">關閉</button>
        		<button class="btn btn-danger" id="action-delete">確定刪除</button>
        	</div>
        </div>
        
        <!-- Modal -->
        <div id="modal-edit" class="modal hide fade" tabindex="-1">
        	<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">×</button>
        		<i class="icon-edit"></i>
        	</div>
        	<div class="modal-body">
        	    <div class="loading"></div>
        	</div>
        	<div class="modal-footer">
        		<button class="btn" data-dismiss="modal">關閉</button>
        		<button class="btn btn-danger" id="action-edit">儲存</button>
        	</div>
        </div>
        
        <div id="modal-alert" class="modal hide fade" tabindex="-1">
        	<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal">×</button>
        		<i class="icon-edit"></i>
        	</div>
        	<div class="modal-body">
        	    <div class="loading"></div>
        	</div>
        	<div class="modal-footer">
        		<button class="btn" data-dismiss="modal">關閉</button>
        	</div>
        </div>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->appendFile($this->basePath() . '/js/modal-submit.js') ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
