<div class="row">
    <form action="" method="post" class="form-horizontal span8 validate-form" style="margin-top:30px;">
        <?php if (isset($this->errorMessage)) : ?>
            <div>
                <label class="alert">
                    <strong><?php echo $this->errorMessage; ?></strong>
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                </label>
            </div>
        <?php endif; ?>
        <div class="control-group">
            <label class="control-label" for="old">輸入舊密碼</label>
            <div class="controls">
                <input id="old" class="input-xlarge" name="old" value="" placeholder="" type="password" data-rule-required="true" data-rule-minlength="6" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="new">輸入新密碼</label>
            <div class="controls">
                <input id="new" class="input-xlarge" name="new" value="" placeholder="請輸入超過六字的英數字" data-rule-required="true" data-rule-minlength="6" type="password" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="check">確認新密碼</label>
            <div class="controls">
                <input id="check" class="input-xlarge" name="check" value="" placeholder="確認您剛剛的新密碼" data-rule-required="true" data-rule-minlength="6" data-rule-equalto="#new" type="password" />
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-danger" type="submit">儲存</button>
            <a href="<?php echo $this->url("admin/default", array("controller" => "profile")); ?>" class="btn">取消</a>
        </div>
        <input name="csrf-token" value="<?php echo $this->csrfToken; ?>" type="hidden" />
    </form>
</div>