<div class="row">
    <form action="" method="post" enctype="multipart/form-data">
        <div class="btn-toolbar span12">
            <button class="btn btn-danger" type="submit">儲存修改</button>
            <a class="btn" href="<?php echo $this->url("admin/default", array("controller" => "profile")); ?>">取消修改</a>
        </div>
        <?php if (count($this->errors) > 0) :?>
        <div class="span12">
            <label class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php for ($i = 0; $i < count($this->errors) - 2; $i++) : ?>
                    <?php echo $this->errors[$i] . "<br/>"; ?>
                <?php endfor; ?>
                <?php echo $this->errors[count($this->errors) - 1]; ?>
            </label>
        </div>
        <?php endif; ?>
        <div class="span4">
            <div class="thumbnail">
                <img src="<?php echo (isset($this->avatar)) ? $this->url("application/default", array("controller" => "image")) . "?" . $this->avatar : ""; ?>" data-src="holder.js/400x400" />
                <input type="file" name="avatar" />
            </div>
        </div>
        <div class="span8">
            <table class="table">
                <tr>
                    <td style="width:40%">帳號</td>
                    <td><?php echo $this->username; ?></td>
                </tr>
                <tr>
                    <td>姓名</td>
                    <td><input type="text" name="name" value="<?php echo $this->name; ?>" /></td>
                </tr>
                <tr>
                    <td>電子信箱</td>
                    <td><input type="email" name="email" value="<?php echo $this->email; ?>" /></td>
                </tr>
                <tr>
                    <td>帳號權限等級</td>
                    <td><?php echo $this->role; ?></td>
                </tr>
                <tr>
                    <td>密碼</td>
                    <td><input type="password" name="password" placeholder="請輸入新密碼" /></td>
                </tr>
            </table>
        </div>
        <input type="hidden" name="t" value="<?php echo $this->t; ?>" />
    </form>
</div>