<div class="row">
    <div class="span12">
        <div class="btn-toolbar">
            <a class="btn" href="<?php echo $this->url("admin/default", array("controller" => "profile", "action" => "edit-avatar")); ?>">修改大頭照</a>
        </div>
    </div>
    <div class="span4">
        <div class="thumbnail">
            <img src="<?php echo (isset($this->avatar)) ? $this->url("application/default", array("controller" => "image")) . "?" . $this->avatar : ""; ?>" data-src="holder.js/400x400" />
        </div>
    </div>
    <div class="span8">
        <table class="table">
            <tr>
                <th>個人資料</th>
                <th>
                    <a class="btn" href="<?php echo $this->url("admin/default", array("controller" => "profile", "action" => "edit")); ?>">修改個人資料</a>
                </th>
            </tr>
            <tr>
                <td style="width:40%">帳號</td>
                <td><?php echo htmlentities($this->username, ENT_QUOTES, "UTF-8"); ?></td>
            </tr>
            <tr>
                <td>姓名</td>
                <td><?php echo htmlentities($this->name, ENT_QUOTES, "UTF-8"); ?></td>
            </tr>
            <tr>
                <td>電子信箱</td>
                <td><?php echo htmlentities($this->email, ENT_QUOTES, "UTF-8"); ?></td>
            </tr>
            <?php if ($this->role == "teacher") : ?>
                <tr>
                    <td>聘雇形式</td>
                    <td><?php echo htmlentities($this->title, ENT_QUOTES, "UTF-8"); ?></td>
                </tr>
                <tr>
                    <td>兼任職稱</td>
                    <td>
                        <?php foreach ($this->othertitles as $i => $othertitle) : ?>
                            <p><?php echo htmlentities($othertitle["title_name"], ENT_QUOTES, "UTF-8"); ?></p>
                        <?php endforeach; ?>
                    </td>
                </tr>
                <tr>
                    <td>指導班級</td>
                    <td><?php echo htmlentities($this->teachClass, ENT_QUOTES, "UTF-8"); ?></td>
                </tr>
                <tr>
                    <td>研究室位置</td>
                    <td><?php echo htmlentities($this->labLocation, ENT_QUOTES, "UTF-8"); ?></td>
                </tr>
                <tr>
                    <td>研究室網頁</td>
                    <td>
                        <a href="<?php echo htmlentities($this->labsiteUrl, ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                            <?php echo htmlentities($this->labsiteText, ENT_QUOTES, "UTF-8"); ?>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>個人網頁</td>
                    <td>
                        <a href="<?php echo htmlentities($this->personalsiteUrl, ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                            <?php echo htmlentities($this->personalsiteText, ENT_QUOTES, "UTF-8"); ?>
                        </a>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td>帳號權限等級</td>
                <td><?php echo $this->role_zhTW; ?></td>
            </tr>
            <tr>
                <th>密碼</th>
                <th><a class="btn btn-danger" href="<?php echo $this->url("admin/default", array("controller" => "profile", "action" => "edit-password")); ?>">修改密碼</a></th>
            </tr>
        </table>
    </div>
</div>