<div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                Sub-navigation
            </a>
        </div>    
        <div class="col-sm-3 col-xs-6 sidebar-offcanvas">
            <form class="input-group search-form" method="get" action="<?php echo $this->url("en_US/default", array("controller" => "faculty")); ?>">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </span>
                <?php if (isset($this->typeId)) : ?>
                    <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                <?php endif; ?>
                <input class="form-control search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="Search professor" />
            </form>
            <ul class="nav nav-list bs-docs-sidenav">
                <li>
                    <a href="<?php echo $this->url("en_US/default", array("controller" => "faculty")); ?>">All</a>
                </li>
                <?php foreach ($this->facultyTitles as $i => $faculty) : ?>
                    <li class="<?php echo ($this->titleId == $faculty["id"]) ? "active" : "" ?>">
                        <a href="<?php echo $this->url("en_US/default", array("controller" => "faculty")) . "?title=" . $faculty["id"]; ?>"><i class="fa fa-chevron-right pull-right"></i><?php echo $faculty["en_US"]; ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header">
                <i class="fa fa-group fa-fw"></i>
                Faculty
            </h4>
            <div class="row">
        	    <div class="col-xs-12">
        	        <?php foreach ($this->faculties as $i => $faculty) : ?>
        	            <div class="row teacher">
        	                <div class="col-sm-4 col-xs-12">
                            	<?php if (isset($faculty["avatar"]) && $faculty["avatar"] != "") : ?>
                            	    <div class="faculty-image-preview" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $faculty["avatar"]; ?>)">
                            	    </div>
                            	<?php else : ?>
                            	    <div class="faculty-image-preview" style="background-image:url(/images/avatar.jpg)">
                            	    </div>
                                <?php endif; ?>
                                <a href="<?php echo $this->url("en_US/default", array("controller" => "faculty", "action" => "profile")) . "?id=" . $faculty["id"]; ?>" class="btn btn-default">
                                    Detailed information
                                    <i class="fa fa-angle-right"></i>
                                </a>
                        	</div>
        	                <div class="col-sm-8 col-xs-12">
            	                <h4 class="margin-top-0">
                                    <?php echo htmlentities($faculty["name"], ENT_QUOTES, "UTF-8"); ?>
                                    <span class="muted"><?php echo htmlentities(trim($faculty["en_US"], "s"), ENT_QUOTES, "UTF-8"); ?></span>
                                </h4>
                                <table class="table">
                                    <?php if (isset($faculty["teach_class"]) && $faculty["teach_class"] != "") : ?>
                                        <tr>
                                            <td>Teach class</td>
                                            <td><?php echo htmlentities($faculty["teach_class"], ENT_QUOTES, "UTF-8"); ?></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr>
                                        <td>Email</td>
                                        <td><?php echo htmlentities($faculty["email"], ENT_QUOTES, "UTF-8"); ?></td>
                                    </tr>
                                    <?php if (isset($faculty["lab_location"]) && $faculty["lab_location"] != "") : ?>
                                        <tr>
                                            <td>Office</td>
                                            <td><?php echo htmlentities($faculty["lab_location"], ENT_QUOTES, "UTF-8"); ?></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr>
                                        <td>Lab website</td>
                                        <td>
                                            <?php if (isset($this->faculty["labsite_url"]) && $this->faculty["labsite_url"] != "") : ?>
                                                <a href="<?php echo htmlentities($this->faculty["labsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                                    <?php echo htmlentities($this->faculty["labsite_text"], ENT_QUOTES, "UTF-8"); ?>
                                                </a>
                                            <?php else : ?>
                                                <a href="#" class="link-disabled">None</a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Personal website</td>
                                        <td>
                                            <?php if (isset($this->faculty["personalsite_url"]) && $this->faculty["personalsite_url"] != "") : ?>
                                            <a href="<?php echo htmlentities($this->faculty["personalsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                                <?php echo htmlentities($this->faculty["personalsite_text"], ENT_QUOTES, "UTF-8"); ?>
                                            </a>
                                            <?php else : ?>
                                                <a href="#" class="link-disabled">None</a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
        	            </div>
                	<?php endforeach; ?>
                </div>
                <div class="col-xs-12">
                    <div class="text-center">
                        <?php echo $this->paginator; ?>
                    </div>
                </div>
        	</div>
        </div>
    </div>
</div>