<div class="container">
    <div class="row" style="margin-top: 10px;">
        <div class="row-fluid span12">
            <div class="span4">
                <?php if (isset($this->faculty["avatar"]) && $this->faculty["avatar"] != "") : ?>
                <img class="img-polaroid featurette-image pull-left" style="height:200px;"
                    src="<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $this->faculty["avatar"]; ?>">
                <?php else : ?>
                    <img class="img-polaroid featurette-image pull-left" style="height:200px;" src="" data-src="holder.js/200x200">
                <?php endif; ?>
            </div>
            <div class="span8">
                <h3>
                    <?php echo htmlentities($this->faculty["name"], ENT_QUOTES, "UTF-8"); ?>
                    <span class="muted"><?php echo htmlentities($this->faculty["en_US"], ENT_QUOTES, "UTF-8"); ?></span>
                </h3>
                <table class="table">
                    <?php if (count($this->othertitles) > 0) : ?>
                        <tr>
                            <td>Other Jobs</td>
                            <td>
                                <?php foreach ($this->othertitles as $i => $othertitle) : ?>
                                    <p><?php echo htmlentities($othertitle["title_name"], ENT_QUOTES, "UTF-8"); ?></p>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($this->faculty["teach_class"]) && $this->faculty["teach_class"] != "") : ?>
                        <tr>
                            <td>Guidance Class</td>
                            <td><?php echo htmlentities($this->faculty["teach_class"], ENT_QUOTES, "UTF-8"); ?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td>Email</td>
                        <td><?php echo htmlentities($this->faculty["email"], ENT_QUOTES, "UTF-8"); ?></td>
                    </tr>
                    <?php if (isset($this->faculty["lab_location"]) && $this->faculty["lab_location"] != "") : ?>
                        <tr>
                            <td>Lab Position</td>
                            <td><?php echo htmlentities($this->faculty["lab_location"], ENT_QUOTES, "UTF-8"); ?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td>Lab Website</td>
                        <td>
                            <?php if (isset($this->faculty["labsite_url"]) && $this->faculty["labsite_url"] != "") : ?>
                                <a href="<?php echo htmlentities($this->faculty["labsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                    <?php echo htmlentities($this->faculty["labsite_text"], ENT_QUOTES, "UTF-8"); ?>
                                </a>
                            <?php else : ?>
                                <a href="#" class="link-disabled">None</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Persional Website</td>
                        <td>
                            <?php if (isset($this->faculty["personalsite_url"]) && $this->faculty["personalsite_url"] != "") : ?>
                            <a href="<?php echo htmlentities($this->faculty["personalsite_url"], ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                                <?php echo htmlentities($this->faculty["personalsite_text"], ENT_QUOTES, "UTF-8"); ?>
                            </a>
                            <?php else : ?>
                                <a href="#" class="link-disabled">None</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <?php foreach ($this->profileTypes as $i => $profileType) : ?>
            <div class="span<?php echo 12 / count($this->profileTypes); ?>">
                <h4><?php echo $profileType["type_en_US"]; ?></h4>
                <table class="table table-hover">
                    <?php foreach ($this->profiles[$profileType["id"]] as $j => $profile) : ?>
                    <tr>
                        <td><?php echo $profile["profile"]; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endforeach; ?>
        <div class="row">
            <div class="span12">
                <h3>RELATIVED</h3>
            </div>
            <div class="span3 bs-docs-sidebar">
                <ul class="nav nav-list bs-docs-sidenav">
                    <?php foreach($this->bookTypes as $i => $bookType): ?>
                        <li class="<?php echo ($bookType["id"] == $this->typeId) ? "active" : ""; ?>">
                            <a href="<?php echo $this->url("en_US/default", array("controller" => "faculty", "action" => "profile")) . "?id=" . $this->id . "&type-id=" . $bookType["id"]; ?>">
                                <i class="icon-chevron-right"></i>
                                <?php echo htmlentities($bookType["type_en_US"], ENT_QUOTES, "UTF-8"); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="span9">
                <table class="table">
                    <?php foreach($this->books as $i => $book): ?>
                        <tr>
                            <td>
                                <?php if (isset($book["url"])) : ?>
                                    <a target="_blank" href="<?php echo htmlentities($book["url"], ENT_QUOTES, "UTF-8"); ?>">
                                        <?php echo htmlentities($book["title"], ENT_QUOTES, "UTF-8"); ?>
                                    </a>
                                <?php else : ?>
                                    <?php echo htmlentities($book["title"], ENT_QUOTES, "UTF-8"); ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>