<div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                Sub-navigation
            </a>
        </div>
        <div class="col-sm-3 col-xs-6 sidebar-offcanvas">
            <div id="nav-side-short" class="introduce bs-docs-sidenav" style="box-shadow:none;">
                <ul class="nav nav-list bs-docs-sidenav">
                    <?php foreach ($this->advanceTypes as $i => $advanceType) : ?>
                        <li class="<?php echo ($this->typeId == $advanceType["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("zh_TW/default", array("controller" => "emba")) . "?type=" . $advanceType["id"]; ?>"><i class="icon-chevron-right"></i><?php echo $advanceType["type_name"]; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header">EMBA</h4>
            <?php echo $this->content; ?>
            <hr>
        </div>
    </div>
</div>