<div class="container">
    <div class="row">
        <div class="span3">
            <div id="nav-side-short" class="introduce bs-docs-sidenav" style="box-shadow:none;">
                <ul class="nav nav-list bs-docs-sidenav">
                    <?php foreach ($this->collectTypes as $i => $collectType) : ?>
                        <li class="<?php echo ($this->typeId == $collectType["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("zh_TW/default", array("controller" => "collect")) . "?type=" . $collectType["id"]; ?>"><i class="icon-chevron-right"></i><?php echo $collectType["type_name"]; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    
        <div class="span9 content">
            <div class="page-header">
                <h3 class="title">大學部</h3>
            </div>
            <hr>
            <?php echo $this->content; ?>
            <hr>
        </div>
    </div>
</div>