<!-- Carousel ================================================== -->
<div id="carousel" class="carousel slide carousel-fade hidden-xs">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <?php foreach($this->slides as $i => $slide) : ?>
            <li data-target="#carousel" data-slide-to="<?php echo $i; ?>" class="<?php echo ($i == 0) ? " active" : ""; ?>"></li>
        <?php endforeach; ?>
    </ol>
	<div class="carousel-inner">
	    <?php foreach ($this->slides as $i => $slide) : ?>
	        <div class="slide-image item<?php echo ($i == 0) ? " active" : ""; ?>" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $slide["image"]; ?>)">
	            <img style="display:none;" alt="preload-slide-image" src="<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $slide["image"]; ?>">
    			<div class="container">
    				<div class="carousel-caption">
    					
    				</div>
    			</div>
    		</div>
	    <?php endforeach; ?>
	</div>
	<!-- Controls -->
    <a class="left carousel-control" href="#carousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>
<!-- /.carousel -->



<!-- Marketing messaging and featurettes
                ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                分類項目
            </a>
        </div>
        <div class="col-sm-3 col-xs-6 sidebar-offcanvas">
            <?php foreach($this->linkTypes as $i => $linkType): ?>
            <h4 class="page-header">
                <i class="fa <?php echo $linkType["icon"]["name"] ?> fa-fw"></i>
                <?php echo $linkType["name"] ?>
            </h4>
            <ul class="nav nav-list bs-docs-sidenav">
                <?php foreach($linkType["links"] as $j => $link): ?>
                <li>
                    <a href="<?php echo $link["url"] ?>" target="_blank">
                        <?php echo $link["name"] ?>
                        <i class="fa fa-chevron-right pull-right"></i>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php endforeach; ?>
        </div>
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header articles-header">
                <i class="fa fa-bullhorn fa-fw"></i>
                最新消息
            </h4>
            <div class="row">
                <?php foreach ($this->articles as $i => $article) : ?>
                <div class="col-xs-12">
                    <div class="article <?php echo ($article["top"] == 1)? "top" : "" ?>">
                        <div class="article-body">
                            <a href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>">
                                <h4>
                                    <?php echo $article["title"]; ?>
                                    <?php if ($article["top"] == 1): ?>
                                        <small class="label label-default">置頂</small>
                                    <?php endif; ?>
                                    <small class="pull-right"><i class="fa fa-clock-o fa-fw"></i><?php echo date("Y /m/d", strtotime($article["time"])); ?></small>
                                </h4>
                            </a>
                            <p class="text-muted"><?php echo $article["content"]; ?></p>
                        </div>
                        <a class="article-view-btn" href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>">
                            <i class="fa fa-angle-right fa-3x"></i>
                        </a>
                    </div>
                </div>
                <?php endforeach; ?>
                <div class="col-xs-12" id="infinity-loader" style="height:50px;background-image:url(<?php echo $this->basePath() . "/images/ajax-loader.gif"; ?>);background-repeat:no-repeat;background-position:center;">
                </div>
            </div>
        </div>
    </div>
</div>
