<?php foreach ($this->articles as $i => $article) : ?>
<div class="col-xs-12">
    <div class="article">
        <div class="article-body">
            <a href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>">
                <h4>
                    <?php echo $article["title"]; ?>
                    <small class="pull-right"><i class="fa fa-clock-o fa-fw"></i><?php echo date("Y /m/d", strtotime($article["time"])); ?></small>
                </h4>
            </a>
            <p class="text-muted"><?php echo $article["content"]; ?></p>
        </div>
        <a class="article-view-btn" href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>">
            <i class="fa fa-angle-right fa-3x"></i>
        </a>
    </div>
</div>
<?php endforeach; ?>