<div class"row">
    <div class="span12">
        <form action="<?php echo $this->url("admin/default", array(
            "controller" => "links",
            "action" => ($this->link["id"] == null)? "create" : "update"
        )); ?>" method="post" class="form">
        <div class="form-group">
            <label for="name">連結名稱</label>
            <div class="controls">
                <input id="name" name="name" type="text" value="<?php echo $this->link["name"] ?>" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label for="url">連結Url</label>
            <div class="controls">
                <input id="url" name="url" type="text" value="<?php echo $this->link["url"] ?>" class="form-control span6" placeholder="http://" />
            </div>
        </div>

        <input name="link_type_id" type="hidden" value="<?php echo $this->link["link_type_id"] ?>" />
        <input name="id" type="hidden" value="<?php echo $this->link["id"] ?>" />

        <div class="form-actions">
            <div class="btn-toolbar">
                <a href="" class="btn btn-default">取消</a>
                <button type="submit" class="btn btn-primary">
                    儲存
                </button>
            </div>
        </div>
        </form>
    </div>
</div>