<div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                Sub-navigation
            </a>
        </div>  
        <div class="col-sm-3 col-xs-12 sidebar-offcanvas">
            <div class="introduce bs-docs-sidenav">
                <ul class="nav nav-list bs-docs-sidenav">
                    <?php foreach ($this->instituteTypes as $i => $instituteType) : ?>
                        <li class="<?php echo ($this->typeId == $instituteType["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("en_US/default", array("controller" => "graduate")) . "?type=" . $instituteType["id"]; ?>">
                                <?php echo $instituteType["type_name"]; ?>
                                <i class="fa fa-chevron-right pull-right"></i>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header">Graduate</h4>
            <?php echo $this->content; ?>
            <hr>
        </div>
    </div>
</div>