<div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-12 visible-xs">
            <a href="#" data-toggle="offcanvas">
                <i class="fa fa-plus-square-o fa-fw"></i>
                分類項目
            </a>
        </div>
        <div class="col-sm-3 col-xs-6 sidebar-offcanvas">
            <form class="input-group search-form" method="get" action="<?php echo $this->url("zh_TW/default", array("controller" => "file", "action" => "search")); ?>">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </span>
                <?php if (isset($this->typeId)) : ?>
                    <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                <?php endif; ?>
                <input class="form-control search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="輸入關鍵字查詢文件" />
            </form>
            <ul class="nav nav-list bs-docs-sidenav">
                <li><a href="<?php echo $this->url("zh_TW/default", array("controller" => "file", "action" => "search")); ?>"><i class="icon-chevron-right"></i>全部</a></li>
                <?php foreach ($this->articleTypes as $i => $articleType) : ?>
                    <li class="<?php echo ($this->typeId == $articleType["id"]) ? "active" : "" ?>">
                        <a href="<?php echo $this->url("zh_TW/default", array("controller" => "file", "action" => "search")) . "?type=" . $articleType["id"]; ?>">
                            <i class="fa fa-chevron-right pull-right"></i>
                            <?php echo $articleType["type_name"]; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header articles-header">
                <?php if (isset($this->term) && $this->term != "") : ?>
                    <i class="fa fa-search fa-fw"></i>查詢結果
                <?php else: ?>
                    <i class="fa fa-file-o fa-fw"></i>文件查找
                <?php endif; ?>
                <span class="pull-right btn-group">
                    <a class="btn btn-default" data-toggle="tooltip" data-placement="top" data-container="body" title="消息列表" href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "index")); ?>"><i class="fa fa-list"></i></a>
                    <a class="btn btn-default active" data-toggle="tooltip" data-placement="top" data-container="body" title="文件查找" href="<?php echo $this->url("zh_TW/default", array("controller" => "file", "action" => "search")); ?>"><i class="fa fa-file"></i></a>
                </span>
            </h4>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th class="col-xs-8">文章標題</th>
                        <th class="col-xs-4">附屬文件</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->downloads as $i => $download) : ?>
                        <tr>
                            <td><?php echo $download["title"]; ?></td>
                            <td>
                                <a class="attach attach-download" href="<?php echo $this->url("application/default", array("controller" => "file")) . "?" . $download["file_name"]; ?>">
                                    <label>
                                        <i class="icon-download-alt"></i>&nbsp;
                                        <span class="highlight">
                                            <?php echo $download["download_name"]; ?>
                                        </span>
                                    </label>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="text-center">
                <?php echo $this->pagination; ?>
            </div>
            <?php if (count($this->similars) > 0) : ?>
                <h4 class="page-header">
                    <i class="fa fa-search-plus fa-fw"></i>
                    以文章標題及內容查詢
                </h4>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="col-xs-8">文章標題</th>
                            <th class="col-xs-4">附屬文件</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->similars as $i => $similar) : ?>
                            <tr>
                                <td class="highlight"><?php echo $similar["title"]; ?></td>
                                <td>
                                    <a class="attach attach-download" href="<?php echo $this->url("application/default", array("controller" => "file")) . "?" . $similar["file_name"]; ?>">
                                        <label>
                                            <i class="icon-download-alt"></i>&nbsp;
                                            <?php echo $similar["download_name"]; ?>
                                        </label>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </div>
</div>