<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
	    <?php foreach ($this->slides as $i => $slide) : ?>
	        <div class="slide-image item<?php echo ($i == 0) ? " active" : ""; ?>" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $slide["image"]; ?>)">
    			<div class="container">
    				<div class="carousel-caption">
    					
    				</div>
    			</div>
    		</div>
	    <?php endforeach; ?>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<!-- /.carousel -->



<!-- Marketing messaging and featurettes
                ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">
    <div class="row">
        <div class="span3">
            <div class="page-header">
                <h3 class="title title-thin">Students Self-learning Societies</h3>
            </div>
            <ul class="nav nav-list side-link">
                <li>
                    <a href="http://imna.im.tku.edu.tw/" target="_blank">
                        <i class="pull-left specials-icon imna"></i>
                        <span class="muted">IMNA</span>
                    </a>
                </li>
                <li>
                    <a href="http://consult.im.tku.edu.tw/" target="_blank">
                        <i class="pull-left specials-icon ico"></i>
                        <span class="muted">ICO</span>
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/TKUB310" target="_blank">
                        <i class="pull-left specials-icon b310"></i>
                        <span class="muted">B310</span>
                    </a>
                </li>
            </ul>
            <div class="page-header">
                <h3 class="title title-thin">University</h3>
            </div>
            <ul class="nav nav-list side-link">
                <li>
                    <a href="http://dsv.su.se/en/" target="_blank">
                        <i class="pull-left specials-icon dsv"></i>
                        <small class="muted">Stockholms<br/>universitet</small>
                    </a>
                </li>
                <li>
                    <a href="http://w3.tku.edu.tw/sister/index_e.asp#main" target="_blank">
                        <i class="pull-left specials-icon ipi"></i>
                        <small class="muted">International<br/>Partner Institution</small>
                    </a>
                </li>
            </ul>
        </div>
        <div class="span9 content">
            <div class="page-header">
                <h3 class="title">News</h3>
            </div>
        	<!-- START THE FEATURETTES -->
        	<div class="row-fluid"  style="margin-top:-5px;">
        	    <div class="span12">
        	        <?php foreach ($this->articles as $i => $article) : ?>
        	            <div class="row-fluid">
        	                <div class="featurette span8">
        	                    <hr>
        	                    <h4 class="timestamp">
        	                        <?php echo date("Y / m / d", strtotime($article["time"])); ?>
        	                    </h4>
                        		<h2 class="featurette-heading">
                        		    <?php echo strip_tags($article["title"]); ?>
                        		</h2>
                        		<p class="featurette-content">
                        		    <?php echo $article["content"]; ?>
                        		</p>
                                <a href="<?php echo $this->url("zh_TW/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>" class="btn">詳細全文</a>
                        	</div>
                        	<div class="span4">
                        	<?php if ($article["title_image"] == "") : ?>
                        	    <hr style="border-width: 3px 0;border-color: #f0f0f7">
                        	<?php endif; ?>
                            	<?php if ($article["title_image"] != "") : ?>
                            	    <div class="article-image-preview" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $article["title_image"]; ?>)">
                            	    </div>
                        	    <?php endif; ?>
                        	</div>
        	            </div>
                	<?php endforeach; ?>
                	<div class="row-fluid" id="infinity-loader" style="height:50px;background-image:url(<?php echo $this->basePath() . "/images/ajax-loader.gif"; ?>);background-repeat:no-repeat;background-position:center;">
                	</div>
                </div>
        	</div>
        	<!-- /END THE FEATURETTES -->
        </div>
    </div>
</div>

