<?php echo $this->doctype(); ?>

<html lang="zh_TW">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('淡江大學 '. $this->translate('資訊管理學系'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/outdatedBrowser.min.css')
                        ->appendStylesheet($this->basePath() . '/css/outdate-show.css')
                        ->appendStylesheet($this->basePath() . '/css/style.css') ?>
    </head>
    <body class="font">
        <!-- header start -->
        <div class="navbar navbar-inverse navbar-fixed-top main-nav full-size">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="big-brand navbar-brand active" href="<?php echo $this->url('home'); ?>">
                        <img alt="淡江大學資訊管理學系" src="/images/tkuim-logo-web-big.png">
                    </a>
                    <a class="small-brand navbar-brand" href="<?php echo $this->url('home'); ?>">
                        <img alt="淡江大學資訊管理學系" src="/images/tkuim-logo-web.png">
                        <label>TKU<span>I</span>M</label>
                    </a>
                </div>
                <div class="collapse navbar-collapse navigation">
                    <?php echo $this->navigation('navigation/default')->menu()->setPartial($partial = array('template/navigation', 'default')) ?>
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <!-- header end -->
        <div>
            <?php echo $this->content; ?>
            <hr>
        </div>
        <div class="container">
            <footer class="row">
                <div class="col-sm-3 col-xs-12">
                    電話: 26215656轉2645或2648<br/>
                    傳真: （02）26209737<br/>
                    E-Mail：tlmx@oa.tku.edu.tw
                </div>
                <div class="col-sm-9 col-xs-12">
                    <a href="<?php echo $this->url("en_US/default"); ?>">English Version</a> &middot; 
                    <!--  <a href="#">關於我們</a> &middot;  -->
                    <a href="http://www.tku.edu.tw/" target="_blank">淡江大學首頁</a> &middot;
                    <a href="http://www.tku.edu.tw/pdp.asp" target="_blank">個資政策</a> &middot;
                    <a href="http://www.tku.edu.tw/notify.asp" target="_blank">個資聲明</a> &middot;
                    <a href="http://www.tku.edu.tw/privacy.asp" target="_blank">隱私權政策</a> &middot;
                    <a href="<?php echo $this->url("admin"); ?>">管理後台</a>
                    <br/>
                    &copy; 2013 CapsLock, <a href="http://calvinpeak.net">Calvin</a> &amp; <a href="http://qugoid.tumblr.com/">Sam</a>.
                </div>
            </footer>
        </div> <!-- /container -->
        
        <!-- outdate browser handle start -->
        <div id="outdated">
            <a href="#" id="btnClose" class="btn pull-right btn-lg" data-dismiss="#outdated"><i class="fa fa-times"></i></a>
            <h3>你的瀏覽器已經過時！</h3>
            <p>快更新你的瀏覽器以獲得正確的網頁顯示</p>
            <a id="btnUpdate" style="display: none;"></a>
            <div class="browsers">
                <div class="browser" id="chrome">
                    <div class="statistic">
                        <h1>37.0%</h1>
                        <p>
                            的網路使用者用這個瀏覽器
                        </p>
                    </div>
                    <div class="logo">
                        <span></span>
                        GOOGLE CHROME
                    </div>
                    <a href="https://www.google.com/chrome/browser/" target="_blank" class="btn btn-download btn-block">
                        取得最新版本
                    </a>
                </div>
                <div class="browser" id="firefox">
                    <div class="statistic">
                        <h1>17.6%</h1>
                        <p>
                            的網路使用者用這個瀏覽器
                        </p>
                    </div>
                    <div class="logo">
                        <span></span>
                        MOZILLA FIREFOX
                    </div>
                    <a href="http://mozilla.com.tw/firefox/new/" target="_blank" class="btn btn-download btn-block">
                        取得最新版本
                    </a>
                </div>
                <div class="browser" id="ie">
                    <div class="statistic">
                        <h1>19.6%</h1>
                        <p>
                            的網路使用者用這個瀏覽器
                        </p>
                    </div>
                    <div class="logo">
                        <span></span>
                        INTERNET EXPLORER
                    </div>
                    <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie" target="_blank" class="btn btn-download btn-block">
                        取得最新版本
                    </a>
                </div>
                <div class="browser" id="safari">
                    <div class="statistic">
                        <h1>16.7%</h1>
                        <p>
                            的網路使用者用這個瀏覽器
                        </p>
                    </div>
                    <div class="logo">
                        <span></span>
                        APPLE SAFARI
                    </div>
                    <a href="http://support.apple.com/downloads/#safari" target="_blank" class="btn btn-download btn-block">
                        取得最新版本
                    </a>
                </div>
                <div class="browser" id="opera">
                    <div class="statistic">
                        <h1>3%</h1>
                        <p>
                            的網路使用者用這個瀏覽器
                        </p>
                    </div>
                    <div class="logo">
                        <span></span>
                        OPERA
                    </div>
                    <a href="http://www.opera.com/zh-tw/computer" target="_blank" class="btn btn-download btn-block">
                        取得最新版本
                    </a>
                </div>
            </div>
        </div>
        <!-- outdate browser handle end -->
        
        <?php echo $this->inlineScript() ?>
        <!-- Scripts -->
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <?php echo $this->headScript()->appendFile($this->basePath() . '/js/outdatedBrowser.min.js', 'text/javascript'); ?>
        <script type="text/javascript">
        $( document ).ready(function() {
            outdatedBrowser({
                bgColor: '#3f3f3f',
                color: '#e3e3e3',
                
            });
            $('#btnClose').on('click', function(){
                $('#outdated').remove();
            });
        });
        </script>
        <script>
            $('.carousel').carousel();
            $(window).on('scroll', function(){
                if ($(window).scrollTop() <= 80) {
                    navbarFullsize();
                } else {
                    navbarSmallsize();
                }
            });
            function navbarFullsize() {
                $('.navbar').addClass('full-size');
                $('.small-brand').removeClass('active');
            }

            function navbarSmallsize() {
                $('.navbar').removeClass('full-size');
                $('.small-brand').addClass('active');
            }
        </script>
    </body>
</html>
