<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <link href="<?php echo $this->basePath("css/bootstrap.min.css"); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basePath("css/style.css"); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basePath("css/admin.css"); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basePath("images/favicon.ico"); ?>" rel="shortcut icon" type="text/css">
        <script src="<?php echo $this->basePath("js/jquery-1.9.1.min.js"); ?>"></script>
        <title>登入界面</title>
    </head>
    <body style="background-color:#444444;">
        <form id="login" name="login" action="<?php echo $this->url("admin/default", array("controller" => "auth", "action" => "login"), true); ?>" method="post">
            <?php if ($this->fail) { ?>
                <div id="hint">賬號或密碼錯誤</div>
            <?php } ?>
            <?php if ($this->overtime) { ?>
                <div id="hint">逾時請重新登入</div>
            <?php } ?>
            <?php if ($this->empty) { ?>
                <div id="hint">請輸入賬號密碼！</div>
            <?php } ?>
            <?php if ($this->tokenEmpty) { ?>
                <div id="hint">驗證碼為空</div>
            <?php } ?>
            <?php if ($this->tokenInvalid) { ?>
                <div id="hint">驗證碼不正確</div>
            <?php } ?>
            <div id="username">
                <input class="field" name="username" type="text" placeholder="請輸入帳號" />
            </div>
            <div id="password">
                <input class="field" name="password" type="password" placeholder="請輸入密碼" />
            </div>
            <div class="row-fluid">
                <button class="btn btn-success span9">登入</button>
                <a class="btn span3" href="<?php echo $this->url("zh_TW/default", array("controller" => "index", "action" => "index")); ?>">取消</a>
            </div>
            <input type="hidden" value="<?php echo $this->token; ?>" name="t" />
            <div id="background-image" style="z-index:-10;position:fixed;top:0;left:0;width:100%;height:100%;background-size:cover;opacity:0;"></div>
        </form>
        <img id="background-source" src="<?php echo $this->basePath("images/login_back.jpg"); ?>" style="display:none;" />
        <script>
            $('#background-source').load(function() {
                var imageSource = $(this).attr('src');
                var imageTarget = $('#background-image');
                imageTarget.css({
                    'background-image' : 'url(' + imageSource + ')',
                });
                imageTarget.animate({
                    'opacity' : 1
                }, 500);
            });
        </script>
    </body>
</html>
