<form class="form-horizontal" method="post" action="<?php echo $this->url("admin/default", array("controller" => "teacher-profile", "action" => "edit-book")) . "?type_id=" . $this->id; ?>">
    <div class="btn-toolbar">
        <button type="submit" class="btn btn-danger">儲存<?php echo $this->typeName; ?></button>
        <a class="btn" href="<?php echo $this->url("admin/default", array("controller" => "teacher-profile", "action" => "book")); ?>">取消更改</a>
    </div>
    <?php foreach ($this->bookList as $key => $value) : ?>
    <div class="control-group">
        <a class="close pull-left" data-dismiss="alert">&times;</a>
        <label class="control-label" for="data-index-<?php echo $key + 1; ?>">標題<?php echo $key + 1; ?></label>
        <div class="controls">
            <input type="text" class="field input-block-level" id="data-index-<?php echo $key + 1; ?>" name="book[]" value="<?php echo $value["title"]; ?>" />
        </div>
    </div>
    <?php endforeach; ?>
    <div class="control-group">
        <a class="close pull-left" data-dismiss="alert">&times;</a>
        <label class="control-label" for="data-index-<?php echo count($this->bookList) + 1; ?>">標題<?php echo count($this->bookList) + 1; ?></label>
        <div class="controls">
            <input type="text" class="field input-block-level" id="data-index-<?php echo count($this->bookList) + 1; ?>" name="book[]" value="" />
        </div>
    </div>
    <input name="t" type="hidden" value="<?php echo $this->token; ?>" />
</form>