<form action="<?php echo $this->url("admin/default", array("controller" => "teacher-profile", "action" => "edit-info")); ?>" method="post">
    <div class="btn-toolbar">
    	<button class="btn btn-danger" type="submit">儲存修改</button>
    	<a class="btn" href="<?php echo $this->url("admin/default", array("controller" => "teacher-profile", "action" => "index")); ?>">取消修改</a>
    	<label class="alert pull-right">
            <a class="close" data-dismiss="alert">&times;</a>
            無資訊可留空
        </label>
    </div>
    <table class="table">
        <tr>
            <td style="width: 40%;">教師職位</td>
            <td>
                <select name="title">
                    <?php foreach ($this->titles as $i => $title) : ?>
                        <option value="<?php echo $title["id"]; ?>" <?php echo ($title["id"] == $this->titleId) ? "selected" : ""; ?>>
                            <?php echo $title["title_name"]; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>其他職位</td>
            <td>
                <?php foreach ($this->othertitles as $i => $othertitle) : ?>
                    <p class="field" style="width:250px;">
                        <input type="text" name="othertitle[]" class="othertitle" value="<?php echo $othertitle["title_name"]; ?>" />
                        <a class="close" data-dismiss="alert">&times;</a>
                    </p>
                <?php endforeach; ?>
                <p class="field" style="width:250px;">
                    <input type="text" name="othertitle[]" class="othertitle" value="" />
                    <a class="close" data-dismiss="alert">&times;</a>
                </p>
            </td>
        </tr>
    	<tr>
    		<td>指導班級</td>
    		<td><input type="text" name="teach-class" value="<?php echo htmlentities($this->teachClass, ENT_QUOTES, "UTF-8"); ?>" /></td>
    	</tr>
    	<tr>
    		<td>研究室位置</td>
    		<td><input type="text" name="lab-location" value="<?php echo htmlentities($this->labLocation, ENT_QUOTES, "UTF-8"); ?>" /></td>
    	</tr>
    	<tr>
    		<td>研究室網頁</td>
    		<td>
    		    <p>
    		        <input type="text" name="labsite-text" value="<?php echo htmlentities($this->labsiteText); ?>" placeholder="網頁名稱" />
    		    </p>
    		    <p>
    		        <input type="text" name="labsite-url" class="input-xxlarge" value="<?php echo htmlentities($this->labsiteUrl); ?>" placeholder="網頁位置" />
    		        <span class="help-block label label-warning"><i class="icon-warning-sign icon-white"></i>&nbsp;請加上http://或是https://</span>
    		    </p>
    		</td>
    	</tr>
    	<tr>
    		<td>個人網頁</td>
    		<td>
    		    <p>
    		        <input type="text" name="personalsite-text" value="<?php echo htmlentities($this->personalsiteText); ?>" placeholder="網頁名稱" />
    		    </p>
    		    <p>
    		        <input type="text" name="personalsite-url" class="input-xxlarge" value="<?php echo htmlentities($this->personalsiteUrl); ?>" placeholder="網頁位置" />
    		        <span class="help-block label label-warning"><i class="icon-warning-sign icon-white"></i>&nbsp;請加上http://或是https://</span>
    		    </p>
    		</td>
    	</tr>
    </table>
    <input type="hidden" name="t" value="<?php echo $this->token; ?>" />
</form>