<div class="row">
    <div class="span12">
        <div class="btn-toolbar">
            <a class="btn btn-primary" href="<?php echo $this->url("admin/default", array("controller" => "teacher-profile", "action" => "edit-info")); ?>">編輯教師資訊</a>
        </div>
        <table class="table">
            <tr>
                <td style="width:40%;">教師職位</td>
                <td><?php echo htmlentities($this->title, ENT_QUOTES, "UTF-8"); ?></td>
            </tr>
            <tr>
                <td>其他職位</td>
                <td>
                    <?php foreach ($this->othertitles as $i => $othertitle) : ?>
                        <p><?php echo htmlentities($othertitle["title_name"], ENT_QUOTES, "UTF-8"); ?></p>
                    <?php endforeach; ?>
                </td>
            </tr>
            <tr>
                <td>指導班級</td>
                <td><?php echo htmlentities($this->teachClass, ENT_QUOTES, "UTF-8"); ?></td>
            </tr>
            <tr>
                <td>研究室位置</td>
                <td><?php echo htmlentities($this->labLocation, ENT_QUOTES, "UTF-8"); ?></td>
            </tr>
            <tr>
                <td>研究室網頁</td>
                <td>
                    <a href="<?php echo htmlentities($this->labsiteUrl, ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                        <?php echo htmlentities($this->labsiteText, ENT_QUOTES, "UTF-8"); ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td>個人網頁</td>
                <td>
                    <a href="<?php echo htmlentities($this->personalsiteUrl, ENT_QUOTES, "UTF-8"); ?>" target="_blank">
                        <?php echo htmlentities($this->personalsiteText, ENT_QUOTES, "UTF-8"); ?>
                    </a>
                </td>
            </tr>
        </table>
    </div>
    <?php foreach ($this->profileTypes as $i => $profileType) : ?>
        <div class="span12">
            <hr>
            <div class="btn-toolbar">
                <a class="btn btn-primary" href="<?php echo $this->url("admin/default", array("controller" => "teacher-profile", "action" => "edit-profile")) . "?type_id=" . $profileType["id"]; ?>">
                    編輯<?php echo $profileType["type_name"]; ?>
                </a>
            </div>
            <table class="table table-striped">
                <?php foreach ($this->profiles[$profileType["id"]] as $j => $profile) : ?>
                <tr>
                    <td><?php echo $profile["profile"]; ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endforeach; ?>
</div>