<div class="container">
    <div class="row">
        <div class="col-sm-3 col-xs-6">
            <div id="nav-side-short" class="introduce bs-docs-sidenav" style="box-shadow:none;">
                <ul class="nav nav-list bs-docs-sidenav">
                    <?php foreach ($this->admissionTypes as $i => $admissionType) : ?>
                        <li class="<?php echo ($this->typeId == $admissionType["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("zh_TW/default", array("controller" => "admission")) . "?type=" . $admissionType["id"]; ?>"><i class="icon-chevron-right"></i><?php echo $admissionType["type_name"]; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    
        <div class="col-sm-9 col-xs-12">
            <h4 class="page-header">招生簡介</h4>
            <?php echo $this->content; ?>
            <hr>
        </div>
    </div>
</div>