<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
	    <?php foreach ($this->slides as $i => $slide) : ?>
	        <div class="slide-image item<?php echo ($i == 0) ? " active" : ""; ?>" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $slide["image"]; ?>)">
    			<div class="container">
    				<div class="carousel-caption">
    					
    				</div>
    			</div>
    		</div>
	    <?php endforeach; ?>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<!-- /.carousel -->



<!-- Marketing messaging and featurettes
                ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">
    <div class="row">
        <div class="span3">
            <div class="page-header">
                <h3 class="title title-thin">學生自治組織</h3>
            </div>
            <ul class="nav nav-list side-link">
                <li>
                    <a href="">
                        <i class="pull-left specials-icon imna"></i>
                        <span class="muted">網路策進協會</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="pull-left specials-icon ico"></i>
                        <span class="muted">資訊顧問室</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="pull-left specials-icon b310"></i>
                        <span class="muted">大學部實驗室</span>
                    </a>
                </li>
            </ul>
            <div class="page-header">
                <h3 class="title title-thin">系所姐妹校</h3>
            </div>
            <ul class="nav nav-list side-link">
                <li>
                    <a href="">
                        <i class="pull-left specials-icon dsv"></i>
                        <small class="muted">瑞典斯德哥爾摩<br/>資訊與系統科學系</small>
                    </a>
                </li>
            </ul>
        </div>
        <div class="span9 content">
            <div class="page-header">
                <h3 class="title">最新消息<span class="muted">NEWS</span></h3>
            </div>
        	<!-- START THE FEATURETTES -->
        	<div class="row-fluid"  style="margin-top:-5px;">
        	    <div class="span12">
        	        <?php foreach ($this->articles as $i => $article) : ?>
        	            <div class="row-fluid">
        	                <div class="featurette span8">
        	                    <hr>
        	                    <h4 class="timestamp">
        	                        <?php echo date("Y / m / d", strtotime($article["time"])); ?>
        	                    </h4>
                        		<h2 class="featurette-heading">
                        		    <?php echo strip_tags($article["title"]); ?>
                        		</h2>
                        		<p class="featurette-content">
                        		    <?php echo $article["content"]; ?>
                        		</p>
                                <a href="<?php echo $this->url("application/default", array("controller" => "news", "action" => "detail")) . "?id=" . $article["id"]; ?>" class="btn">詳細全文</a>
                        	</div>
                        	<div class="span4">
                            	<?php if ($article["title_image"] != "") : ?>
                            	    <div class="article-image-preview" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $article["title_image"]; ?>)">
                            	    </div>
                        	    <?php endif; ?>
                        	</div>
        	            </div>
                	<?php endforeach; ?>
                </div>
        	</div>
        	<!-- /END THE FEATURETTES -->
        </div>
    </div>
</div>

