<form class="form-horizontal" method="post" action="<?php echo $this->url("admin/default", array("controller" => "teacher", "action" => "booktype")); ?>">
    <div class="btn-toolbar">
        <button type="submit" class="btn btn-danger">儲存更動</button>
        <a id="auto-fill" class="btn" href="<?php echo $this->url("admin/default", array("controller" => "teacher", "action" => "get-type")); ?>">從教師評鑑系統截取</a>
    </div>
    <?php if ($this->saveSuccess) :?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <i class="icon-ok"></i>&nbsp;儲存成功
    </div>
    <?php else : ?>
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <i class="icon-resize-vertical"></i>&nbsp;按住滑鼠左鍵拉動項目可以進行排序
    </div>
    <?php endif; ?>
    <div id="type-sort">
        <?php foreach ($this->booktypeList as $key => $value) : ?>
            <div class="control-group">
                <button type="button" class="close pull-left" data-dismiss="alert">&times;</button>
                <label class="control-label" for="data-index-<?php echo $key + 1; ?>">項目<?php echo $key + 1; ?></label>
                <div class="controls controls-row">
                    <input type="text" class="field" id="data-index-<?php echo $key + 1; ?>" name="type[]" value="<?php echo $value["type_name"]; ?>" placeholder="項目顯示名稱" />
                    <input type="text" class="field" name="type_en_US[]" value="<?php echo $value["type_en_US"]; ?>" placeholder="分類英文顯示名稱" />
                    <input type="text" class="field" name="value[]" value="<?php echo $value["type_value"]; ?>" placeholder="教師歷程系統分類值" />
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="control-group unsave">
        <label class="control-label">項目</label>
        <div class="controls controls-row">
            <input type="text" class="field" name="type[]" value="" placeholder="項目顯示名稱" />
            <input type="text" class="field" name="type_en_US[]" value="" placeholder="分類英文顯示名稱" />
            <input type="text" class="field" name="value[]" value="" placeholder="教師歷程系統分類值" /> 
        </div>
    </div>
</form>