<table class="table">
    <thead>
        <tr>
            <th>教師名稱</th>
            <th>聘雇形式</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->teachers as $i => $teacher) : ?>
            <tr>
                <td><?php echo htmlentities($teacher["name"], ENT_QUOTES, "UTF-8"); ?></td>
                <td>
                    <select>
                        <?php foreach ($this->titles as $j => $title) : ?>
                            
                        <?php endforeach; ?>
                    </select>
                </td>
                <td>
                    
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>