<div class="container">
    <div class="row">
        <div class="span3">
            <div id="nav-side" class="bs-docs-sidenav" style="box-shadow:none;">
                <form class="input-prepend" method="get" action="<?php echo $this->url("application/default", array("controller" => "faculty")); ?>">
                    <button type="submit" class="btn"><i class="icon-search"></i></button>
                    <input class="search input-block-level" type="text" name="term" value="<?php echo htmlentities($this->term, ENT_QUOTES, "UTF-8"); ?>" placeholder="輸入關鍵字查詢消息" />
                    <?php if (isset($this->typeId)) : ?>
                        <input type="hidden" name="type" value="<?php echo htmlentities($this->typeId, ENT_QUOTES, "UTF-8"); ?>" />
                    <?php endif; ?>
                </form>
                <ul class="nav nav-list bs-docs-sidenav">
                    <li><a href="<?php echo $this->url("application/default", array("controller" => "faculty")); ?>"><i class="icon-chevron-right"></i>全部</a></li>
                    <?php foreach ($this->facultyTitles as $i => $faculty) : ?>
                        <li class="<?php echo ($this->titleId == $faculty["id"]) ? "active" : "" ?>">
                            <a href="<?php echo $this->url("application/default", array("controller" => "faculty")) . "?title=" . $faculty["id"]; ?>"><i class="icon-chevron-right"></i><?php echo $faculty["title_name"]; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    
        <div class="content span9">
            <div class="page-header">
                <h3 class="title">教師陣容</h3>
            </div>
            <div class="row-fluid"  style="margin-top: 20px;">
        	    <div class="span12">
        	        <?php foreach ($this->faculties as $i => $faculty) : ?>
        	            <div class="row-fluid">
        	                <div class="featurette span8">
        	                    <hr>
            	                <h2 class="featurette-heading">
                                    <?php echo htmlentities($faculty["name"], ENT_QUOTES, "UTF-8"); ?>
                                    <span class="muted"><?php echo htmlentities($faculty["title_name"], ENT_QUOTES, "UTF-8"); ?></span>
                                </h2>
                                <table class="table">
                                    <tr>
                                        <td style="width:45%;">擔任職位</td>
                                        <td><?php echo htmlentities($faculty["title_name"], ENT_QUOTES, "UTF-8"); ?></td>
                                    </tr>
                                    <?php if (count($faculty["other_title"]) > 0) : ?>
                                        <tr>
                                            <td>其他職位</td>
                                            <td>
                                            <?php foreach ($faculty["other_title"] as $i => $otherTitle) : ?>
                                                <p><?php echo htmlentities($otherTitle["title_name"], ENT_QUOTES, "UTF-8"); ?></p>
                                            <?php endforeach;?>
                                            </td>
                                        </tr>
                                    <?php endif; ?>
                                    <?php if (isset($faculty["teach_class"]) && $faculty["teach_class"] != "") : ?>
                                        <tr>
                                            <td>指導班級</td>
                                            <td><?php echo htmlentities($faculty["teach_class"], ENT_QUOTES, "UTF-8"); ?></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr>
                                        <td>電子信箱</td>
                                        <td><?php echo htmlentities($faculty["email"], ENT_QUOTES, "UTF-8"); ?></td>
                                    </tr>
                                    <?php if (isset($faculty["lab_location"]) && $faculty["lab_location"] != "") : ?>
                                        <tr>
                                            <td>研究室位置</td>
                                            <td><?php echo htmlentities($faculty["lab_location"], ENT_QUOTES, "UTF-8"); ?></td>
                                        </tr>
                                    <?php endif; ?>
                                </table>
                                <a href="<?php echo $this->url("application/default", array("controller" => "faculty", "action" => "profile")) . "?id=" . $faculty["id"]; ?>" class="btn">詳細個人介紹</a>
                            </div>
                        	<div class="span4">
                            	<?php if (isset($faculty["avatar"]) && $faculty["avatar"] != "") : ?>
                            	    <div class="faculty-image-preview" style="background-image:url(<?php echo $this->url("application/default", array("controller" => "image")) . "?" . $faculty["avatar"]; ?>)">
                            	    </div>
                                <?php endif; ?>
                        	</div>
        	            </div>
                	<?php endforeach; ?>
                	<div class="pagination pagination-centered">
                        <?php echo $this->paginator; ?>
                    </div>
                </div>
        	</div>
        </div>
    </div>
</div>